name: Build lsfg-vk on Flatpak
on: workflow_dispatch
jobs:
  flatpak:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime-version: [23.08, 24.08]
        branch: ['develop', 'test/fp16']
        include:
          - runtime-version: 23.08
            container-image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
          - runtime-version: 24.08
            container-image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
    container:
      image: ${{ matrix.container-image }}
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Generate manifest
        run: |
          cd flatpak
          make RUNTIME_VERSION=${{ matrix.runtime-version }} BRANCH=${{ matrix.branch }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.freedesktop.Platform.VulkanLayer.lsfgvk-${{ matrix.runtime-version }}-${{ replace(matrix.branch, '/', '_') }}.flatpak
          manifest-path: flatpak/org.freedesktop.Platform.VulkanLayer.lsfgvk.yml
